In [47]:
import numpy as np
a=np.arange(10)
print(a)
print("\n")
b=np.arange(9,-1,-1)
print(b)

[0 1 2 3 4 5 6 7 8 9]


[9 8 7 6 5 4 3 2 1 0]


In [54]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a)
print("\n")
b=a.reshape(9,-1)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [102]:
a=np.zeros((10,10))
a[0]=1
a[:10,0]=1
a[9]=1
a[:10,9]=1
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [114]:
a=np.zeros((5,5))
a[::2,1::2]=1
a[1::2,0::2]=1
a

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [139]:
a=np.arange(10)
print(a)
a[5:9:1] = -a[5:9:1]
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, -5, -6, -7, -8,  9])

In [116]:
x=np.array([[4,5],[7,10]])
y=np.array([[2,3],[1,5]])
result=x@y
result

array([[13, 37],
       [24, 71]])